#!/bin/bash

# Extractions and Copy files
echo "Check update."
sudo apt-get update
echo "Install Open-SSH server in your Ubuntu."
sudo apt install openssh-server
echo "SSHD is active."
sudo systemctl enable sshd
echo "Copy main config"
sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.factory-defaults
# Needed replacements
sudo sed -i 's/Port 22/Port 4000/g' /etc/ssh/sshd_config
sudo sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
# Time of autorization
sudo sed -i 's/LoginGraceTime 120/LoginGraceTime 60/g' /etc/ssh/sshd_config
# Allows users
sudo sed -i 's/AllowUsers /AllowUsers user0 sftpuser/g' /etc/ssh/sshd_config
echo "Restart ssh"
sudo systemctl restart ssh
echo "Ufw allows port 4000 for ssh"
sudo ufw allow ssh
sudo ufw allow 4000
